# -*- coding: utf-8 -*-
"""
继续翻译 - 补充steps, coaching, avoid字段翻译
"""
import os

source_path = 'munger-models-zh.html'
target_path = 'munger-models-zh.html'

with open(source_path, 'r', encoding='utf-8') as f:
    html = f.read()

# 翻译steps中的常见短语
steps_map = {
    'Identify Your Map': '识别你的地图',
    'Clearly define the model, plan, or set of beliefs': '清楚地定义你用于理解情况的模型、计划或信念集',
    'Acknowledge its Limitations': '承认其局限性',
    'Remind yourself that this map is a simplified representation': '提醒自己这个地图是简化的表征',
    'Seek Out the Territory': '寻找领土',
    'Actively gather real-world, direct evidence': '主动收集真实世界的直接证据',
    'Compare and Contrast': '比较和对比',
    'How does the real-world evidence differ from your map': '真实世界的证据与你的地图有何不同',
    'Update Your Map': '更新你的地图',
    'Adjust your model, plan, or beliefs based on the new information': '根据你收集的新信息调整你的模型、计划或信念',
    'Define Your Core Competencies': '定义你的核心能力',
    'Make a list of subjects, skills, or industries where you have genuine, deep expertise': '列出你通过经验和学习建立的真正深入的专业知识的主题、技能或行业',
    'Define Your Boundaries': '定义你的边界',
    'Be explicit about what you don\'t know': '明确你不知道什么',
    'Operate Within the Circle': '在圈子内运作',
    'When making high-stakes decisions': '当做高风险决策时',
    'Expand the Circle Deliberately': '有意识地扩展圈子',
    'If you need to venture into a new area': '如果你需要进入新领域',
    'Consult Experts': '咨询专家',
    'When a decision must be made outside your circle': '当必须在圈子外做决策时',
    'Identify the Problem': '识别问题',
    'Clearly state the problem you are trying to solve': '清楚地陈述你试图解决的问题',
    'Deconstruct the Problem': '解构问题',
    'Break the problem down into its most basic components': '将问题分解为最基本的组件',
    'Challenge Every Assumption': '挑战每个假设',
    'Question the conventional wisdom and assumptions': '质疑围绕每个组件的传统智慧和假设',
    'Reconstruct from the Ground Up': '从零重建',
    'Using the verified fundamental truths': '使用验证的基本真理',
    'Optimize the New Solution': '优化新解决方案',
    'Refine your new approach based on logic and evidence': '基于逻辑和证据而非传统来完善你的新方法',
    'Define the Scenario': '定义场景',
    'Clearly state the hypothesis or decision you want to explore': '清楚地陈述你想探索的假设或决策',
    'Establish the Conditions': '建立条件',
    'Set the initial parameters and constraints': '设定实验的初始参数和约束',
    'Run the Simulation': '运行模拟',
    'Mentally play out the scenario': '在脑海中演练场景',
    'Explore Consequences': '探索后果',
    'Consider the immediate outcomes': '考虑即时结果',
    'Draw Conclusions': '得出结论',
    'What did you learn from the simulation': '你从模拟中学到了什么',
    'Identify the Decision and First-Order Consequence': '识别决策和一阶后果',
    'State the action you are considering': '陈述你正在考虑的行动',
    'Ask And then what': '问然后呢',
    'What happens as a result of that first consequence': '第一个后果的结果是什么',
    'Continue Asking And then what': '继续问然后呢',
    'Trace the chain of effects further': '进一步追溯效应链',
    'Consider the Full System': '考虑整个系统',
    'Think about how your decision will affect other parts': '思考你的决策将如何影响系统的其他部分',
    'Evaluate the Full Chain of Consequences': '评估完整后果链',
    'Weigh the desirable first-order effect': '权衡理想的一阶效应',
    'Acknowledge Uncertainty': '承认不确定性',
    'Accept that most outcomes are not 100% certain': '接受大多数结果不是100%确定的',
    'Identify Potential Outcomes': '识别潜在结果',
    'List all the possible results': '列出决策或事件的所有可能结果',
    'Estimate Probabilities': '估计概率',
    'Use available data, historical precedent, and logical reasoning': '使用可用数据、历史先例和逻辑推理',
    'Consider the Payoff': '考虑收益',
    'For each outcome, determine the potential gain or loss': '为每个结果确定潜在收益或损失',
    'Calculate Expected Value': '计算期望值',
    'Multiply the probability of each outcome by its payoff': '将每个结果的概率乘以其收益并求和',
    'Decide Based on Favorable Odds': '基于有利赔率决策',
    'Make the decision that has the best combination': '做出具有高概率和正收益最佳组合的决策',
    'Clearly Define Your Goal': '清楚地定义你的目标',
    'State what you want to achieve': '陈述你想达到什么',
    'Invert the Problem': '逆向问题',
    'Flip the goal on its head': '把目标翻转过来',
    'Brainstorm All Potential Failure Points': '头脑风暴所有潜在失败点',
    'List every possible mistake, obstacle, and bad decision': '列出可能导致失败的每一个可能的错误、障碍和糟糕决策',
    'Create an Avoidance List': '创建避免清单',
    'From your brainstormed list, create a clear set of rules': '从你头脑风暴的清单中，创建一套清晰的规则',
    'Focus on Not Being Stupid': '专注于不愚蠢',
    'By focusing your energy on avoiding the things on your list': '通过将精力集中在避免清单上的事情',
    'Observe a Negative Outcome': '观察负面结果',
    'Notice a situation where someone\'s action has caused a problem': '注意某人的行动造成问题的情境',
    'Resist the Malice Assumption': '抵制恶意假设',
    'Your immediate emotional reaction might be to assume': '你的即时情绪反应可能是假设',
    'Brainstorm Alternative Explanations': '头脑风暴替代解释',
    'What other factors could have led to this outcome': '还有什么因素可能导致这个结果',
    'Default to the Most Charitable Explanation': '默认为最善意解释',
    'Assume the most likely cause is a non-malicious one': '假设最可能的原因是非恶意的',
    'Respond with Curiosity, Not Accusation': '以好奇而非指责回应',
    'Approach the person to understand their perspective': '接近对方以了解他们的观点',
    'Gather All Plausible Explanations': '收集所有合理的解释',
    'List all the different hypotheses or theories': '列出可以解释你观察到的现象的所有不同假设或理论',
    'Count the Assumptions': '计算假设',
    'For each explanation, identify and count': '为每个解释，识别并计算',
    'Identify the Simplest Explanation': '识别最简单的解释',
    'The explanation that relies on the fewest assumptions': '依赖最少新、未验证假设的解释',
    'Test the Simplest Explanation First': '首先检验最简单的解释',
    'Before diving into complex theories': '在深入研究复杂理论之前',
    'Identify the Hump': '识别坎儿',
    'What is the initial barrier or point of friction': '阻止你开始的初始障碍或摩擦点是什么',
    'Lower the Barrier': '降低门槛',
    'Break the initial task down into the smallest possible step': '将初始任务分解为最小的可能步骤',
    'Apply Focused Energy': '施加专注能量',
    'Dedicate a specific, uninterrupted block of time': '专门分配一个不间断的时间块',
    'Don\'t Worry About the Finish Line': '不用担心终点',
    'The goal is not to complete the entire task': '目标不是完成整个任务',
    'Harness the Momentum': '利用势头',
    'Once you\'ve started, use the momentum': '一旦你开始了，利用势头推动你前进',
}

for en, zh in steps_map.items():
    html = html.replace(en, zh)

# 翻译coaching问题
coaching_map = {
    'What is the map we are using to make this decision': '我们用于做这个决策的地图是什么',
    'What assumptions are built into this model or plan': '这个模型或计划中嵌入了什么假设',
    'How can we get a more direct look at the actual situation': '我们如何能更直接地了解实际情况',
    'What information might our data be missing': '我们的数据可能缺少什么信息',
    'If our plan were to fail, what part of reality would we have likely misjudged': '如果我们的计划失败，我们可能误判了现实的哪部分',
    'Is this decision within our core area of expertise': '这个决策在我们的核心专业领域内吗',
    'On a scale of 1-10, how well do you truly understand this subject': '在1-10的量表上，你真正理解这个主题的程度如何',
    'Could you explain the arguments of the opposing side better than they could': '你能比反对者更好地解释他们的论点吗',
    'What are the unknown unknowns for us in this situation': '我们在这种情况下的未知未知是什么',
    'Are we making this decision based on genuine competence or on a feeling of confidence': '我们是基于真正的能力还是基于信心感来做这个决策的',
    'What are the fundamental truths or facts of this situation': '这个情况的基本真理或事实是什么',
    'Why do we believe this has to be done this way': '为什么我们相信这必须这样做',
    'What if we were starting from a blank slate': '如果我们从一个空白石板开始',
    'What are the raw materials of this problem': '这个问题的原材料是什么',
    'Let\'s pretend we\'re explaining this to a five-year-old': '假设我们在向一个五岁孩子解释这个',
    'Let\'s imagine we go ahead with this plan': '让我们想象我们推进这个计划',
    'Walk me through what happens next, step by step': '一步步带我看接下来会发生什么',
    'What is the absolute worst-case scenario': '绝对最坏场景是什么',
    'If we had a magic wand and could see the outcome': '如果我们有魔法棒，能看到结果',
    'What factors have we not considered': '我们没有考虑什么因素',
    'How would this decision affect our finances, stress levels, and relationships': '这个决策如何影响我们的财务、压力水平和关系',
    'That\'s the immediate benefit. What happens after that': '那是即时好处。然后呢',
    'What are the potential ripple effects of this decision': '这个决策的潜在涟漪效应是什么',
    'Who else will be affected by this, and how might they react': '还有谁会受到这个影响，他们可能如何反应',
    'What is a likely unintended consequence of this action': '这个行动的一个可能的意外后果是什么',
    'Instead of asking if this will work, let\'s ask how likely it is to work': '与其问这是否会成功，让我们问有多可能成功',
    'What are the three most likely outcomes here': '这里最可能的三个结果是什么',
    'What\'s the difference between a bad decision and a bad outcome': '糟糕决策和糟糕结果之间的区别是什么',
    'Even if this has a high probability of success, what is the cost if we are wrong': '即使这有高成功概率，如果我们错了，成本是什么',
    'What information could we gather that would help us make a more accurate probability estimate': '我们可以收集什么信息帮助我们做出更准确的概率估计',
    'Let\'s imagine this project is a complete disaster a year from now': '让我们想象一年后这个项目完全失败',
    'What would have caused that': '是什么原因导致的',
    'Instead of designing the perfect day, what would a truly miserable day look like': '与其设计完美的一天，真正糟糕的一天会是什么样子',
    'What are all the stupid things we could do to ruin this opportunity': '我们可能做哪些愚蠢的事情来毁掉这个机会',
    'What key things must we not do if we want to succeed': '如果我们想成功，我们必须不做哪些关键事情',
    'If we wanted to guarantee we lose our biggest client, what actions would we take': '如果我们想保证失去最大的客户，我们会采取什么行动',
    'Before we assume they are trying to sabotage us': '在我们假设他们试图破坏我们之前',
    'what are some other possible explanations for their behavior': '他们行为的一些其他可能解释是什么',
    'Is it possible this was just an honest mistake': '这可能只是一个诚实错误吗',
    'What might be going on in their world that could have led to this oversight': '他们的世界中可能发生了什么导致了这个疏忽',
    'If we assume good intent, how does that change our interpretation': '如果我们假设善意意图，这如何改变我们的解读',
    'Could this be explained by a simple miscommunication': '这可以用简单的误解来解释吗',
    'What is the absolute simplest possible explanation for this': '这绝对最简单的可能解释是什么',
    'Which of these theories requires us to believe the fewest new things': '这些理论中哪一个要求我们相信最少的新事情',
    'Are we making this more complicated than it needs to be': '我们是否把这变得比需要的更复杂',
    'Before we assume a complex conspiracy, have we ruled out a simple mistake': '在我们假设复杂阴谋之前，我们排除了简单错误吗',
    'What is the most direct cause-and-effect relationship we can see here': '我们能在这里看到的最直接的因果关系是什么',
    'What is the smallest possible step you could take to get this started': '你可以采取的最小可能步骤是什么来启动这个',
    'What\'s the one thing that\'s making it feel so hard to begin': '让开始感觉如此困难的那个东西是什么',
    'How can we make the first 10 minutes of this task as easy as possible': '我们如何使这个任务的前10分钟尽可能容易',
    'What would it look like if we just focused on getting over the initial hump': '如果我们只是专注于越过初始坎儿，那会是什么样子',
    'Are we failing to start because the activation energy is too high': '我们未能启动是因为活化能太高吗',
}

for en, zh in coaching_map.items():
    html = html.replace(en, zh)

# 保存
with open(target_path, 'w', encoding='utf-8') as f:
    f.write(html)

print(f"补充翻译完成！文件大小: {os.path.getsize(target_path)/1024:.1f}KB")